# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts_form.ui'
#
# Created: Tue Jun  2 16:34:50 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_frmContacts(object):
    def setupUi(self, frmContacts):
        frmContacts.setObjectName("frmContacts")
        frmContacts.resize(767, 600)
        self.centralWidget = QtGui.QWidget(frmContacts)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidgetContacts = QtGui.QTreeWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetContacts.sizePolicy().hasHeightForWidth())
        self.treeWidgetContacts.setSizePolicy(sizePolicy)
        self.treeWidgetContacts.setObjectName("treeWidgetContacts")
        self.treeWidgetContacts.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidgetContacts)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblPicture = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPicture.sizePolicy().hasHeightForWidth())
        self.lblPicture.setSizePolicy(sizePolicy)
        self.lblPicture.setMinimumSize(QtCore.QSize(150, 150))
        self.lblPicture.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblPicture.setText("")
        self.lblPicture.setObjectName("lblPicture")
        self.horizontalLayout_2.addWidget(self.lblPicture)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblLastname = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(14)
        self.lblLastname.setFont(font)
        self.lblLastname.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblLastname.setText("")
        self.lblLastname.setObjectName("lblLastname")
        self.verticalLayout_2.addWidget(self.lblLastname)
        self.lblFirstname = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFirstname.sizePolicy().hasHeightForWidth())
        self.lblFirstname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(14)
        self.lblFirstname.setFont(font)
        self.lblFirstname.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblFirstname.setText("")
        self.lblFirstname.setObjectName("lblFirstname")
        self.verticalLayout_2.addWidget(self.lblFirstname)
        self.lblOrganization = QtGui.QLabel(self.centralWidget)
        self.lblOrganization.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblOrganization.setText("")
        self.lblOrganization.setObjectName("lblOrganization")
        self.verticalLayout_2.addWidget(self.lblOrganization)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidgetMulitvalue = QtGui.QListWidget(self.centralWidget)
        self.listWidgetMulitvalue.setObjectName("listWidgetMulitvalue")
        self.verticalLayout_4.addWidget(self.listWidgetMulitvalue)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        frmContacts.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 22))
        self.menubar.setObjectName("menubar")
        frmContacts.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmContacts)
        self.statusbar.setObjectName("statusbar")
        frmContacts.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmContacts)
        self.toolBar.setObjectName("toolBar")
        frmContacts.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(frmContacts)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/data/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExtract = QtGui.QAction(frmContacts)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/data/img/unzip_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract.setIcon(icon1)
        self.actionExtract.setObjectName("actionExtract")
        self.actionReport = QtGui.QAction(frmContacts)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/data/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon2)
        self.actionReport.setObjectName("actionReport")
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExtract)
        self.toolBar.addAction(self.actionReport)

        self.retranslateUi(frmContacts)
        QtCore.QObject.connect(self.treeWidgetContacts, QtCore.SIGNAL("clicked(QModelIndex)"), frmContacts.onTreeClick)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), frmContacts.close)
        QtCore.QObject.connect(self.actionExtract, QtCore.SIGNAL("activated()"), frmContacts.extractApp)
        QtCore.QObject.connect(self.actionReport, QtCore.SIGNAL("activated()"), frmContacts.printReport)
        QtCore.QMetaObject.connectSlotsByName(frmContacts)

    def retranslateUi(self, frmContacts):
        frmContacts.setWindowTitle(QtGui.QApplication.translate("frmContacts", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmContacts", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("frmContacts", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("frmContacts", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("frmContacts", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setText(QtGui.QApplication.translate("frmContacts", "Extract DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setToolTip(QtGui.QApplication.translate("frmContacts", "Extract Contacts Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setShortcut(QtGui.QApplication.translate("frmContacts", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setText(QtGui.QApplication.translate("frmContacts", "Print Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setToolTip(QtGui.QApplication.translate("frmContacts", "Print HTML Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setShortcut(QtGui.QApplication.translate("frmContacts", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))

import iosbackupexaminer2_rc
