# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_window2.ui'
#
# Created: Fri May 22 15:08:56 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/data/img/apple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayoutInfoView = QtGui.QGridLayout()
        self.gridLayoutInfoView.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayoutInfoView.setObjectName("gridLayoutInfoView")
        self.label_15 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayoutInfoView.addWidget(self.label_15, 7, 2, 1, 1)
        self.lblIMEI = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIMEI.sizePolicy().hasHeightForWidth())
        self.lblIMEI.setSizePolicy(sizePolicy)
        self.lblIMEI.setMinimumSize(QtCore.QSize(300, 0))
        self.lblIMEI.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblIMEI.setFrameShadow(QtGui.QFrame.Plain)
        self.lblIMEI.setText("")
        self.lblIMEI.setObjectName("lblIMEI")
        self.gridLayoutInfoView.addWidget(self.lblIMEI, 6, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayoutInfoView.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayoutInfoView.addWidget(self.label_16, 8, 2, 1, 1)
        self.lblProductVersion = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProductVersion.sizePolicy().hasHeightForWidth())
        self.lblProductVersion.setSizePolicy(sizePolicy)
        self.lblProductVersion.setMinimumSize(QtCore.QSize(300, 0))
        self.lblProductVersion.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblProductVersion.setFrameShadow(QtGui.QFrame.Plain)
        self.lblProductVersion.setText("")
        self.lblProductVersion.setObjectName("lblProductVersion")
        self.gridLayoutInfoView.addWidget(self.lblProductVersion, 3, 3, 1, 1)
        self.lblProductType = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProductType.sizePolicy().hasHeightForWidth())
        self.lblProductType.setSizePolicy(sizePolicy)
        self.lblProductType.setMinimumSize(QtCore.QSize(300, 0))
        self.lblProductType.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblProductType.setFrameShadow(QtGui.QFrame.Plain)
        self.lblProductType.setText("")
        self.lblProductType.setObjectName("lblProductType")
        self.gridLayoutInfoView.addWidget(self.lblProductType, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayoutInfoView.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayoutInfoView.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayoutInfoView.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayoutInfoView.addWidget(self.label_10, 1, 2, 1, 1)
        self.lblDisplayName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDisplayName.sizePolicy().hasHeightForWidth())
        self.lblDisplayName.setSizePolicy(sizePolicy)
        self.lblDisplayName.setMinimumSize(QtCore.QSize(300, 0))
        self.lblDisplayName.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblDisplayName.setFrameShadow(QtGui.QFrame.Plain)
        self.lblDisplayName.setText("")
        self.lblDisplayName.setObjectName("lblDisplayName")
        self.gridLayoutInfoView.addWidget(self.lblDisplayName, 3, 1, 1, 1)
        self.lblGUID = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGUID.sizePolicy().hasHeightForWidth())
        self.lblGUID.setSizePolicy(sizePolicy)
        self.lblGUID.setMinimumSize(QtCore.QSize(300, 0))
        self.lblGUID.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblGUID.setFrameShadow(QtGui.QFrame.Plain)
        self.lblGUID.setText("")
        self.lblGUID.setObjectName("lblGUID")
        self.gridLayoutInfoView.addWidget(self.lblGUID, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayoutInfoView.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayoutInfoView.addWidget(self.label_5, 4, 0, 1, 1)
        self.lblUniqueIdentifier = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUniqueIdentifier.sizePolicy().hasHeightForWidth())
        self.lblUniqueIdentifier.setSizePolicy(sizePolicy)
        self.lblUniqueIdentifier.setMinimumSize(QtCore.QSize(300, 0))
        self.lblUniqueIdentifier.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblUniqueIdentifier.setFrameShadow(QtGui.QFrame.Plain)
        self.lblUniqueIdentifier.setText("")
        self.lblUniqueIdentifier.setObjectName("lblUniqueIdentifier")
        self.gridLayoutInfoView.addWidget(self.lblUniqueIdentifier, 7, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayoutInfoView.addWidget(self.label_7, 6, 0, 1, 1)
        self.lblSerialNumber = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialNumber.sizePolicy().hasHeightForWidth())
        self.lblSerialNumber.setSizePolicy(sizePolicy)
        self.lblSerialNumber.setMinimumSize(QtCore.QSize(300, 0))
        self.lblSerialNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblSerialNumber.setFrameShadow(QtGui.QFrame.Plain)
        self.lblSerialNumber.setText("")
        self.lblSerialNumber.setObjectName("lblSerialNumber")
        self.gridLayoutInfoView.addWidget(self.lblSerialNumber, 4, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayoutInfoView.addWidget(self.label_14, 6, 2, 1, 1)
        self.lblBuildVersion = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBuildVersion.sizePolicy().hasHeightForWidth())
        self.lblBuildVersion.setSizePolicy(sizePolicy)
        self.lblBuildVersion.setMinimumSize(QtCore.QSize(300, 0))
        self.lblBuildVersion.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblBuildVersion.setFrameShadow(QtGui.QFrame.Plain)
        self.lblBuildVersion.setText("")
        self.lblBuildVersion.setObjectName("lblBuildVersion")
        self.gridLayoutInfoView.addWidget(self.lblBuildVersion, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setFrameShadow(QtGui.QFrame.Raised)
        self.label_17.setObjectName("label_17")
        self.gridLayoutInfoView.addWidget(self.label_17, 0, 0, 1, 4)
        self.lblTargetIdentifier = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTargetIdentifier.sizePolicy().hasHeightForWidth())
        self.lblTargetIdentifier.setSizePolicy(sizePolicy)
        self.lblTargetIdentifier.setMinimumSize(QtCore.QSize(300, 0))
        self.lblTargetIdentifier.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblTargetIdentifier.setFrameShadow(QtGui.QFrame.Plain)
        self.lblTargetIdentifier.setText("")
        self.lblTargetIdentifier.setObjectName("lblTargetIdentifier")
        self.gridLayoutInfoView.addWidget(self.lblTargetIdentifier, 5, 3, 1, 1)
        self.lblProductName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProductName.sizePolicy().hasHeightForWidth())
        self.lblProductName.setSizePolicy(sizePolicy)
        self.lblProductName.setMinimumSize(QtCore.QSize(300, 0))
        self.lblProductName.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblProductName.setFrameShadow(QtGui.QFrame.Plain)
        self.lblProductName.setText("")
        self.lblProductName.setObjectName("lblProductName")
        self.gridLayoutInfoView.addWidget(self.lblProductName, 1, 3, 1, 1)
        self.lblMEID = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMEID.sizePolicy().hasHeightForWidth())
        self.lblMEID.setSizePolicy(sizePolicy)
        self.lblMEID.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMEID.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblMEID.setFrameShadow(QtGui.QFrame.Plain)
        self.lblMEID.setText("")
        self.lblMEID.setObjectName("lblMEID")
        self.gridLayoutInfoView.addWidget(self.lblMEID, 7, 1, 1, 1)
        self.lbliTunesVersion = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbliTunesVersion.sizePolicy().hasHeightForWidth())
        self.lbliTunesVersion.setSizePolicy(sizePolicy)
        self.lbliTunesVersion.setMinimumSize(QtCore.QSize(300, 0))
        self.lbliTunesVersion.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbliTunesVersion.setFrameShadow(QtGui.QFrame.Plain)
        self.lbliTunesVersion.setText("")
        self.lbliTunesVersion.setObjectName("lbliTunesVersion")
        self.gridLayoutInfoView.addWidget(self.lbliTunesVersion, 8, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayoutInfoView.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayoutInfoView.addWidget(self.label_3, 2, 0, 1, 1)
        self.lblDeviceName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDeviceName.sizePolicy().hasHeightForWidth())
        self.lblDeviceName.setSizePolicy(sizePolicy)
        self.lblDeviceName.setMinimumSize(QtCore.QSize(300, 0))
        self.lblDeviceName.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblDeviceName.setFrameShadow(QtGui.QFrame.Plain)
        self.lblDeviceName.setText("")
        self.lblDeviceName.setObjectName("lblDeviceName")
        self.gridLayoutInfoView.addWidget(self.lblDeviceName, 2, 1, 1, 1)
        self.lblPhoneNumber = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPhoneNumber.sizePolicy().hasHeightForWidth())
        self.lblPhoneNumber.setSizePolicy(sizePolicy)
        self.lblPhoneNumber.setMinimumSize(QtCore.QSize(300, 0))
        self.lblPhoneNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblPhoneNumber.setFrameShadow(QtGui.QFrame.Plain)
        self.lblPhoneNumber.setText("")
        self.lblPhoneNumber.setObjectName("lblPhoneNumber")
        self.gridLayoutInfoView.addWidget(self.lblPhoneNumber, 8, 1, 1, 1)
        self.lblTargetType = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTargetType.sizePolicy().hasHeightForWidth())
        self.lblTargetType.setSizePolicy(sizePolicy)
        self.lblTargetType.setMinimumSize(QtCore.QSize(300, 0))
        self.lblTargetType.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblTargetType.setFrameShadow(QtGui.QFrame.Plain)
        self.lblTargetType.setText("")
        self.lblTargetType.setObjectName("lblTargetType")
        self.gridLayoutInfoView.addWidget(self.lblTargetType, 6, 3, 1, 1)
        self.lblICCID = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblICCID.sizePolicy().hasHeightForWidth())
        self.lblICCID.setSizePolicy(sizePolicy)
        self.lblICCID.setMinimumSize(QtCore.QSize(300, 0))
        self.lblICCID.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblICCID.setFrameShadow(QtGui.QFrame.Plain)
        self.lblICCID.setText("")
        self.lblICCID.setObjectName("lblICCID")
        self.gridLayoutInfoView.addWidget(self.lblICCID, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayoutInfoView.addWidget(self.label, 5, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayoutInfoView.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayoutInfoView.addWidget(self.label_9, 8, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayoutInfoView)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayoutManifestView = QtGui.QGridLayout()
        self.gridLayoutManifestView.setObjectName("gridLayoutManifestView")
        self.lblVersion = QtGui.QLabel(self.centralwidget)
        self.lblVersion.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblVersion.setText("")
        self.lblVersion.setObjectName("lblVersion")
        self.gridLayoutManifestView.addWidget(self.lblVersion, 5, 1, 1, 1)
        self.lblHasBackupKeybag = QtGui.QLabel(self.centralwidget)
        self.lblHasBackupKeybag.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblHasBackupKeybag.setText("")
        self.lblHasBackupKeybag.setObjectName("lblHasBackupKeybag")
        self.gridLayoutManifestView.addWidget(self.lblHasBackupKeybag, 3, 1, 1, 1)
        self.lblWasPasscodeSet = QtGui.QLabel(self.centralwidget)
        self.lblWasPasscodeSet.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblWasPasscodeSet.setText("")
        self.lblWasPasscodeSet.setObjectName("lblWasPasscodeSet")
        self.gridLayoutManifestView.addWidget(self.lblWasPasscodeSet, 6, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayoutManifestView.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayoutManifestView.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayoutManifestView.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayoutManifestView.addWidget(self.label_21, 4, 0, 1, 1)
        self.lblSystemDomainsVersion = QtGui.QLabel(self.centralwidget)
        self.lblSystemDomainsVersion.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblSystemDomainsVersion.setText("")
        self.lblSystemDomainsVersion.setObjectName("lblSystemDomainsVersion")
        self.gridLayoutManifestView.addWidget(self.lblSystemDomainsVersion, 4, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.centralwidget)
        self.lblDate.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblDate.setText("")
        self.lblDate.setObjectName("lblDate")
        self.gridLayoutManifestView.addWidget(self.lblDate, 1, 1, 1, 1)
        self.lblIsEncrypted = QtGui.QLabel(self.centralwidget)
        self.lblIsEncrypted.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblIsEncrypted.setText("")
        self.lblIsEncrypted.setObjectName("lblIsEncrypted")
        self.gridLayoutManifestView.addWidget(self.lblIsEncrypted, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayoutManifestView.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayoutManifestView.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setFrameShape(QtGui.QFrame.Panel)
        self.label_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_24.setObjectName("label_24")
        self.gridLayoutManifestView.addWidget(self.label_24, 0, 0, 1, 2)
        self.horizontalLayout_8.addLayout(self.gridLayoutManifestView)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 3, 1, 2)
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(0, 0))
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 2, 2, 1, 3)
        self.treeViewDomains = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeViewDomains.sizePolicy().hasHeightForWidth())
        self.treeViewDomains.setSizePolicy(sizePolicy)
        self.treeViewDomains.setObjectName("treeViewDomains")
        self.treeViewDomains.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeViewDomains, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1205, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuReopen = QtGui.QMenu(self.menuFile)
        self.menuReopen.setObjectName("menuReopen")
        self.menu_Reports = QtGui.QMenu(self.menuBar)
        self.menu_Reports.setObjectName("menu_Reports")
        self.menu_View = QtGui.QMenu(self.menuBar)
        self.menu_View.setCursor(QtCore.Qt.WhatsThisCursor)
        self.menu_View.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menu_View.setSeparatorsCollapsible(False)
        self.menu_View.setObjectName("menu_View")
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menuExtract = QtGui.QMenu(self.menuBar)
        self.menuExtract.setObjectName("menuExtract")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_OpenBackup = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/data/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OpenBackup.setIcon(icon1)
        self.action_OpenBackup.setObjectName("action_OpenBackup")
        self.action_CloseBackup = QtGui.QAction(MainWindow)
        self.action_CloseBackup.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/data/img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CloseBackup.setIcon(icon2)
        self.action_CloseBackup.setObjectName("action_CloseBackup")
        self.action_Quit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/data/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon3)
        self.action_Quit.setObjectName("action_Quit")
        self.action_About = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/data/img/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon4)
        self.action_About.setObjectName("action_About")
        self.action_Preferences = QtGui.QAction(MainWindow)
        self.action_Preferences.setObjectName("action_Preferences")
        self.action_ExtractApp = QtGui.QAction(MainWindow)
        self.action_ExtractApp.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/data/img/unzip_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ExtractApp.setIcon(icon5)
        self.action_ExtractApp.setObjectName("action_ExtractApp")
        self.action_ExtractAll = QtGui.QAction(MainWindow)
        self.action_ExtractAll.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/data/img/unzip_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ExtractAll.setIcon(icon6)
        self.action_ExtractAll.setObjectName("action_ExtractAll")
        self.action_Contacts = QtGui.QAction(MainWindow)
        self.action_Contacts.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/data/img/contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Contacts.setIcon(icon7)
        self.action_Contacts.setObjectName("action_Contacts")
        self.action_CallHistory = QtGui.QAction(MainWindow)
        self.action_CallHistory.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Images/data/img/callhistory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CallHistory.setIcon(icon8)
        self.action_CallHistory.setObjectName("action_CallHistory")
        self.action_Messages = QtGui.QAction(MainWindow)
        self.action_Messages.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Images/data/img/message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Messages.setIcon(icon9)
        self.action_Messages.setObjectName("action_Messages")
        self.action_Threema = QtGui.QAction(MainWindow)
        self.action_Threema.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Images/data/img/threema.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Threema.setIcon(icon10)
        self.action_Threema.setObjectName("action_Threema")
        self.action_WhatsApp = QtGui.QAction(MainWindow)
        self.action_WhatsApp.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Images/data/img/whatsapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_WhatsApp.setIcon(icon11)
        self.action_WhatsApp.setObjectName("action_WhatsApp")
        self.separatorMRUList = QtGui.QAction(MainWindow)
        self.separatorMRUList.setObjectName("separatorMRUList")
        self.menuReopen.addAction(self.separatorMRUList)
        self.menuFile.addAction(self.action_Preferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuReopen.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_OpenBackup)
        self.menuFile.addAction(self.action_CloseBackup)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuFile.addSeparator()
        self.menu.addAction(self.action_About)
        self.menuExtract.addAction(self.action_ExtractApp)
        self.menuExtract.addAction(self.action_ExtractAll)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuExtract.menuAction())
        self.menuBar.addAction(self.menu_Reports.menuAction())
        self.menuBar.addAction(self.menu_View.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.action_Quit)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_OpenBackup)
        self.toolBar.addAction(self.action_CloseBackup)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_About)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Contacts)
        self.toolBar.addAction(self.action_CallHistory)
        self.toolBar.addAction(self.action_Messages)
        self.toolBar.addAction(self.action_Threema)
        self.toolBar.addAction(self.action_WhatsApp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ExtractApp)
        self.toolBar.addAction(self.action_ExtractAll)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.action_About, QtCore.SIGNAL("activated()"), MainWindow.displayAbout)
        QtCore.QObject.connect(self.action_Contacts, QtCore.SIGNAL("activated()"), MainWindow.showContacts)
        QtCore.QObject.connect(self.action_CallHistory, QtCore.SIGNAL("activated()"), MainWindow.showCallHistory)
        QtCore.QObject.connect(self.action_Messages, QtCore.SIGNAL("activated()"), MainWindow.showMessages)
        QtCore.QObject.connect(self.action_Threema, QtCore.SIGNAL("activated()"), MainWindow.showThreema)
        QtCore.QObject.connect(self.action_WhatsApp, QtCore.SIGNAL("activated()"), MainWindow.showWhatsapp)
        QtCore.QObject.connect(self.action_ExtractApp, QtCore.SIGNAL("activated()"), MainWindow.extractApp)
        QtCore.QObject.connect(self.action_ExtractAll, QtCore.SIGNAL("activated()"), MainWindow.extractAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "iOS Backup Examiner", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Unique Identifier:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Serial Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "iTunes Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Product Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Product Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "MEID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Produkt Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "ICCID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "GUID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "IMEI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Target Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Info.plist Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Display Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Device Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Target Identifier:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Build Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Phone Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Has Backup Keybag:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Passcode set:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "System Domains Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Is Encrypted:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Manifest.plist Information", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuReopen.setTitle(QtGui.QApplication.translate("MainWindow", "Reopen...", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Reports.setTitle(QtGui.QApplication.translate("MainWindow", "&Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "&?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExtract.setTitle(QtGui.QApplication.translate("MainWindow", "Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_OpenBackup.setText(QtGui.QApplication.translate("MainWindow", "&Open Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.action_OpenBackup.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_CloseBackup.setText(QtGui.QApplication.translate("MainWindow", "&Close Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.action_CloseBackup.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Preferences.setText(QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Preferences.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ExtractApp.setText(QtGui.QApplication.translate("MainWindow", "Extract selected App", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ExtractAll.setText(QtGui.QApplication.translate("MainWindow", "Extract all files", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Contacts.setText(QtGui.QApplication.translate("MainWindow", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.action_CallHistory.setText(QtGui.QApplication.translate("MainWindow", "Call History", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Messages.setText(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Messages.setToolTip(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Threema.setText(QtGui.QApplication.translate("MainWindow", "Threema", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Threema.setToolTip(QtGui.QApplication.translate("MainWindow", "Threema", None, QtGui.QApplication.UnicodeUTF8))
        self.action_WhatsApp.setText(QtGui.QApplication.translate("MainWindow", "WhatsApp", None, QtGui.QApplication.UnicodeUTF8))
        self.action_WhatsApp.setToolTip(QtGui.QApplication.translate("MainWindow", "WhatsApp", None, QtGui.QApplication.UnicodeUTF8))
        self.separatorMRUList.setText(QtGui.QApplication.translate("MainWindow", "separatorMRUList", None, QtGui.QApplication.UnicodeUTF8))

import iosbackupexaminer2_rc
