# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threema_form.ui'
#
# Created: Tue Jun  9 15:12:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_frmThreema(object):
    def setupUi(self, frmThreema):
        frmThreema.setObjectName("frmThreema")
        frmThreema.resize(1031, 669)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/data/img/threema.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmThreema.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(frmThreema)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetContacts = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetContacts.sizePolicy().hasHeightForWidth())
        self.tableWidgetContacts.setSizePolicy(sizePolicy)
        self.tableWidgetContacts.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetContacts.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetContacts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetContacts.setObjectName("tableWidgetContacts")
        self.tableWidgetContacts.setColumnCount(0)
        self.tableWidgetContacts.setRowCount(0)
        self.tableWidgetContacts.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidgetContacts, 0, 0, 1, 2)
        self.tableWidgetChats = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetChats.sizePolicy().hasHeightForWidth())
        self.tableWidgetChats.setSizePolicy(sizePolicy)
        self.tableWidgetChats.setMinimumSize(QtCore.QSize(600, 0))
        self.tableWidgetChats.setObjectName("tableWidgetChats")
        self.tableWidgetChats.setColumnCount(0)
        self.tableWidgetChats.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetChats, 1, 0, 1, 1)
        self.tableWidgetMessages = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetMessages.sizePolicy().hasHeightForWidth())
        self.tableWidgetMessages.setSizePolicy(sizePolicy)
        self.tableWidgetMessages.setObjectName("tableWidgetMessages")
        self.tableWidgetMessages.setColumnCount(0)
        self.tableWidgetMessages.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetMessages, 1, 1, 1, 1)
        frmThreema.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmThreema)
        self.statusbar.setObjectName("statusbar")
        frmThreema.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmThreema)
        self.toolBar.setObjectName("toolBar")
        frmThreema.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExtract = QtGui.QAction(frmThreema)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/data/img/unzip_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract.setIcon(icon1)
        self.actionExtract.setObjectName("actionExtract")
        self.actionReport = QtGui.QAction(frmThreema)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/data/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon2)
        self.actionReport.setObjectName("actionReport")
        self.actionQuit = QtGui.QAction(frmThreema)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/data/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExtract)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReport)

        self.retranslateUi(frmThreema)
        QtCore.QObject.connect(self.tableWidgetContacts, QtCore.SIGNAL("currentItemChanged(QTableWidgetItem*,QTableWidgetItem*)"), frmThreema.onTreeClick)
        QtCore.QObject.connect(self.actionExtract, QtCore.SIGNAL("activated()"), frmThreema.extractApp)
        QtCore.QObject.connect(self.actionReport, QtCore.SIGNAL("activated()"), frmThreema.printReport)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), frmThreema.close)
        QtCore.QMetaObject.connectSlotsByName(frmThreema)

    def retranslateUi(self, frmThreema):
        frmThreema.setWindowTitle(QtGui.QApplication.translate("frmThreema", "Threema Report", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetContacts.setSortingEnabled(True)
        self.tableWidgetChats.setSortingEnabled(True)
        self.tableWidgetMessages.setSortingEnabled(True)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmThreema", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setText(QtGui.QApplication.translate("frmThreema", "Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setToolTip(QtGui.QApplication.translate("frmThreema", "Extract Threema App", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setShortcut(QtGui.QApplication.translate("frmThreema", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setText(QtGui.QApplication.translate("frmThreema", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setToolTip(QtGui.QApplication.translate("frmThreema", "Create HTML Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setShortcut(QtGui.QApplication.translate("frmThreema", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("frmThreema", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("frmThreema", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

import iosbackupexaminer2_rc
