# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'whatsapp_form.ui'
#
# Created: Tue Jun  9 14:32:23 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_frmWhatsapp(object):
    def setupUi(self, frmWhatsapp):
        frmWhatsapp.setObjectName("frmWhatsapp")
        frmWhatsapp.resize(938, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/data/img/whatsapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmWhatsapp.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(frmWhatsapp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableViewContacts = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewContacts.sizePolicy().hasHeightForWidth())
        self.tableViewContacts.setSizePolicy(sizePolicy)
        self.tableViewContacts.setMinimumSize(QtCore.QSize(100, 0))
        self.tableViewContacts.setObjectName("tableViewContacts")
        self.verticalLayout_3.addWidget(self.tableViewContacts)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableViewChats = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewChats.sizePolicy().hasHeightForWidth())
        self.tableViewChats.setSizePolicy(sizePolicy)
        self.tableViewChats.setMinimumSize(QtCore.QSize(500, 0))
        self.tableViewChats.setObjectName("tableViewChats")
        self.verticalLayout_4.addWidget(self.tableViewChats)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableViewMessages = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewMessages.sizePolicy().hasHeightForWidth())
        self.tableViewMessages.setSizePolicy(sizePolicy)
        self.tableViewMessages.setMinimumSize(QtCore.QSize(400, 0))
        self.tableViewMessages.setObjectName("tableViewMessages")
        self.verticalLayout_6.addWidget(self.tableViewMessages)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 1, 1, 3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelPicture = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPicture.sizePolicy().hasHeightForWidth())
        self.labelPicture.setSizePolicy(sizePolicy)
        self.labelPicture.setMinimumSize(QtCore.QSize(150, 150))
        self.labelPicture.setText("")
        self.labelPicture.setObjectName("labelPicture")
        self.verticalLayout_5.addWidget(self.labelPicture)
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(150, 0))
        self.labelStatus.setMaximumSize(QtCore.QSize(150, 180))
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_5.addWidget(self.labelStatus)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableViewPhones = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewPhones.sizePolicy().hasHeightForWidth())
        self.tableViewPhones.setSizePolicy(sizePolicy)
        self.tableViewPhones.setObjectName("tableViewPhones")
        self.horizontalLayout.addWidget(self.tableViewPhones)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 2, 1, 2)
        frmWhatsapp.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmWhatsapp)
        self.statusbar.setObjectName("statusbar")
        frmWhatsapp.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmWhatsapp)
        self.toolBar.setObjectName("toolBar")
        frmWhatsapp.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExtract = QtGui.QAction(frmWhatsapp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/data/img/unzip_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract.setIcon(icon1)
        self.actionExtract.setObjectName("actionExtract")
        self.actionReport = QtGui.QAction(frmWhatsapp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/data/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon2)
        self.actionReport.setObjectName("actionReport")
        self.actionQuit = QtGui.QAction(frmWhatsapp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/data/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExtract)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReport)

        self.retranslateUi(frmWhatsapp)
        QtCore.QObject.connect(self.actionExtract, QtCore.SIGNAL("activated()"), frmWhatsapp.extractApp)
        QtCore.QObject.connect(self.actionReport, QtCore.SIGNAL("activated()"), frmWhatsapp.printReport)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), frmWhatsapp.close)
        QtCore.QObject.connect(self.tableViewContacts, QtCore.SIGNAL("clicked(QModelIndex)"), frmWhatsapp.onTreeClickContacts)
        QtCore.QObject.connect(self.tableViewChats, QtCore.SIGNAL("clicked(QModelIndex)"), frmWhatsapp.onTreeClickChats)
        QtCore.QMetaObject.connectSlotsByName(frmWhatsapp)

    def retranslateUi(self, frmWhatsapp):
        frmWhatsapp.setWindowTitle(QtGui.QApplication.translate("frmWhatsapp", "WhatsApp Report", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmWhatsapp", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setText(QtGui.QApplication.translate("frmWhatsapp", "Extract Threema", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setToolTip(QtGui.QApplication.translate("frmWhatsapp", "Extract Threema App", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract.setShortcut(QtGui.QApplication.translate("frmWhatsapp", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setText(QtGui.QApplication.translate("frmWhatsapp", "HTML Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setToolTip(QtGui.QApplication.translate("frmWhatsapp", "Create HTML Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport.setShortcut(QtGui.QApplication.translate("frmWhatsapp", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("frmWhatsapp", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("frmWhatsapp", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

import iosbackupexaminer2_rc
